name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest
      - name: Send mail on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ Pipeline Sukces: ${{ github.repository }}"
          to: bartoszwisniewski91@gmail.com
          from: GitHub Actions
          body: |
            Wdrożenie zakończone sukcesem!!!
            Commit: ${{ github.sha }}
            Autor: ${{ github.actor }}
            Link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send mail on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "❌ Pipeline BŁĄD: ${{ github.repository }}"
          to: bartoszwisniewski91@gmail.com
          from: GitHub Actions
          body: |
            Pojawił się błąd podczas wdrażania.
            Sprawdź logi tutaj: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
        run: |
          mkdir -p ~/app
          cp docker-compose.yml ~/app/
          [ -d "monitoring" ] && cp -r monitoring/ ~/app/ || echo "No monitoring folder"
          
          cd ~/app
          echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" > .env
          
          docker compose pull
          docker compose up -d --force-recreate