name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./app  # Ścieżka do folderu z pom.xml i kodem
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,monitoring/"
          target: "~/app"

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            docker-compose pull
            docker-compose up -d

      - name: Send Discord Notification
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 Deployment status: ${{ job.status }}!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}